name: GitHub Contribution Calendar

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  calendar:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate contribution calendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/contributions.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 1
